version: '3.8'
services:  
  db:
    image: postgres:15    
    container_name: postgres_container
    environment:      
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password      
      POSTGRES_DB: mydb
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    ports:      
      - "5434:5432"
  web:
    build: .    
    container_name: django_container
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]    
    volumes:
      - .:/app    
    ports:
      - "8000:8000"    
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
volumes:  
  postgres_data: