name: Django CI/CD Pipeline 
on:     
  push: 
    branches:             
      - main 
  pull_request:         
    branches: 
      - main 
jobs:     
  build: 
    runs-on: ubuntu-latest         
    services: 
      postgres:                 
        image: postgres:13 
        env:           
          POSTGRES_DB: mydb           
          POSTGRES_USER: user           
          POSTGRES_PASSWORD: password         
        ports:           
          - 5433:5432         
        options: --health-cmd="pg_isready -U user" --health-timeout=5s --health-retries=3     
    steps:       
      - name: Checkout repository         
        uses: actions/checkout@v2 
      - name: Set up Python                 
        uses: actions/setup-python@v2 
        with:                     
          python-version: '3.11'
      - name: Install docker-compose
        run: |          
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Install dependencies                 
        run: | 
          python -m pip install --upgrade pip                     
          pip install -r requirements.txt 
      - name: Run migrations         
        run: |           
          docker-compose -f docker-compose.yml run web python manage.py migrate       
      - name: Run tests 
        run: |                     
          docker-compose -f docker-compose.yml run web python manage.py test 
      - name: Build Docker container         
        run: |           
          docker-compose -f docker-compose.yml build       

      - name: Push Docker images to registry         
        if: github.ref == 'refs/heads/main'         
        run: |           
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}           
          docker-compose -f docker-compose.yml push